### ISSUE TITLE
一些改良建议

### ISSUE THREAD

**Issue by weiyinfu** [wilds9/Mini-Cube-God-s-Number-Verification#1]
1. MainClass没必要单独一个包，改到一个包里面更好
2. Cube.java文件中，把魔方5040=7！个位置映射成int时，应该写成for循环，你看你写的这个太low了。

**Comment by wildsandalwood9** [comment]
第一条的确是，因为我接触java很少，不太懂文件命名规则，当初不知道怎么处理MainClass改名字、放到哪个位置的问题；
第二条建议，可能是对的，我不确定有没有更好的、同时又很省运行时间的写法，我记不清几年前写代码时遇到的具体问题了。

由于第一版（C语言）运行了9小时，所以后来改进时注意力主要放在耗时的语句上，没怎么关注简洁的问题（并且改成简洁的会面临会不会增大运算量的问题），再加上自己本身水平非常业余，所以出现了这样的现象； 后来C语言运行时间缩短到15分钟上下的样子，再后来为了练习java而移植成了现在的java版，我对这个程序已经没什么别的追求，我还是先不改了……

**Comment by wildsandalwood9** [comment]
作者最近要用Fortran，常常追忆java，因为用过java再用Fortran简直像是在考古。由于这个原因，我不能再碰java，那样会让我更抵触Fortran……

**Comment by wilds9** [comment]
非常感谢提出建议！

第一条的确是，因为我接触java很少，不太懂文件命名规则（这个程序就是为了学习java而从三年前的C代码移植过来的），当初学习java不清楚怎么处理MainClass改名字、放到哪个位置的问题；

第二条建议，是说getNum_A()方法，我看了下，我印象中这个地方最初是很简洁的，但是，为了省运算时间，不得不改写成现在的样子。关于运算时间：第一版（C语言）运行了9小时，后来缩短到15分钟上下的样子（再后来为了练习java而移植成了现在的java版）；

高手应该有既简洁又省时的写法，但是我本人水平业余，就不再这一点上继续尝试了；另外一个缘故：因为最近要用Fortran，常常追忆java语法，因为用过java再用Fortran简直像是在考古。所以我不能再碰java，那样会让我更抵触Fortran……

**Comment by wilds9** [comment]
已经重写
